run:
  concurrency: 1
  deadline: 5m
  tests: false

linters:
  enable:
    - golint
    - lll
    - dupl

issues:
  exclude-use-default: false
  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

service:
  golangci-lint-version: 1.19.x